Add sample to get access token by oauth
andregasser/bigbone pull request #195
Opened 2023-04-26 06:01 UTC by lamrongol

Modify: add redirectUri

2023-04-26 11:50 UTC, andregasser requested changes
Hello @lamrongol, sorry for the long wait time. I just had another look at this PR and I think it would be best to have your code in the repo as a working example in the sample-* modules instead of just listing it in USAGE.md. Could you eventually provide a new piece of sample code to the sample-java module (separate file?). Reason: We would like to remove the USAGE.md sooner or later. If you don't have the time to so it, I could do it. Just let me know. Thank you! 😊

2023-04-26 12:09 UTC, lamrongol commented
OK, but what should the file name, etc. be? If I should simply cut and paste the code somewhere else, it would be easy and I want to leave it to you.

2023-04-26 12:19 UTC, andregasser commented
You could name it 'OAuthGetAccessToken.java'. Thank you very much!

2023-04-28 09:57 UTC, lamrongol commented
I modified. Kotlin code is converted by IntelliJ IDEA and I confirmed it works.

2023-04-28 10:59 UTC, andregasser commented on sample-kotlin/src/main/kotlin/social/bigbone/sample/OAuthGetAccessToken.kt
> +import java.util.*
Please replace star import with java.util.Scanner

2023-04-28 11:00 UTC, andregasser requested changes
Thanks for providing the sample code! I have just added a minor comment to your PR. After fixing this, I will happily merge it into the repo.

2023-04-28 13:06 UTC, lamrongol commented
"Unresolved conversations" is still displayed for some reason, but this has been fixed.

2023-04-28 13:08 UTC, andregasser approved these changes

2023-04-28 13:08 UTC, merged

2023-04-28 13:09 UTC, andregasser commented
Thanks @lamrongol for fixing this so quick!